### ISSUE TITLE
Failed to start concord_ethrpc node

### ISSUE THREAD

**Issue by thpun** [vmware/concord#45]
Failed to start concord_ethrpc node. Getting a JAVA error:
```
2021-03-08 06:59:52,135 main ERROR JsonLayout contains an invalid element or attribute "objectMessageAsJsonObject"
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/exc/InputCoercionException
        at org.apache.logging.log4j.core.jackson.Initializers$SimpleModuleInitializer.initialize(Initializers.java:84)
        at org.apache.logging.log4j.core.jackson.Log4jJsonModule.<init>(Log4jJsonModule.java:46)
        at org.apache.logging.log4j.core.jackson.Log4jJsonObjectMapper.<init>(Log4jJsonObjectMapper.java:43)
        at org.apache.logging.log4j.core.layout.JacksonFactory$JSON.newObjectMapper(JacksonFactory.java:77)
        at org.apache.logging.log4j.core.layout.JacksonFactory.newWriter(JacksonFactory.java:230)
        at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:145)
        at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:70)
        at org.apache.logging.log4j.core.layout.JsonLayout$Builder.build(JsonLayout.java:97)
        at org.apache.logging.log4j.core.layout.JsonLayout$Builder.build(JsonLayout.java:78)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:958)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:898)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:890)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:890)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:513)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:237)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:249)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:155)
        at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
        at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
        at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:189)
        at com.vmware.concord.ethrpc.Application.main(Application.java:17)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.exc.InputCoercionException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 39 more
```

## Steps to reproduce

1. Follow the Get Started instruction in README:
```bash
git clone https://github.com/vmware/concord
cd concord
docker/build_images.sh
docker-compose -f docker/compose/simple4.yml up
```

2. Docker container of concord_ethrpc returned the above error and exited.

Please insert instructions on how to reproduce the issue here. The example should be minimal, complete and verifiable (see https://stackoverflow.com/help/mcve).

## Context

 - Used versions (Concord version): commit `85862f8b6a079d3e5db989d7934aee2cd42ba46b`
 - Docker version: 17.09.0-ce, build afdb6d4
 - Docker-compose version: 1.27.4, build 40524192
 - Host OS: Ubuntu 16.04.3

**Comment by sandyk12276** [comment]
What worked for me i have mentioned in below steps:
step1: navigate to folder concord-> tools-> ethrpc  in your local installation.
step2: change the version no. from 2.9.10 to 2.10.0 of the following dependency in pom.xml file as below.

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            
            <version>2.10.0</version>
        </dependency>

step3: run the below commands again

       docker/build_images.sh
       docker-compose -f docker/compose/simple4.yml up

Finally with this the build was successfull and i was able to run the 4-node concord in my system
